<?php

$dbconn = pg_connect("host=localhost port=5432 dbname=carsdb user=admin password=12345")
or die('Не удалось соединиться c субд: ' . pg_last_error());

require __DIR__ . '/../../config/db.php';

$query = "SELECT * FROM users";
$result = pg_query($query) or die('Ошибка запроса: ' . pg_last_error());

$qcars = "SELECT id, nameauto from cars";
$cars = pg_query($qcars) or die('Ошибка запроса: ' . pg_last_error());

if (isset($_POST[login1]) and isset($_POST[password1]) and isset($_POST[mail1]) and ($_POST[login1] != '' and $_POST[password1] != '' and $_POST[mail1] != '')){
    $odb['login'] = $_POST[login1];
    $odb['password'] = $_POST[password1];
    $odb['mail'] = $_POST[mail1];
    $odb['phone'] = $_POST[phone1];
    $odb['city'] = $_POST[city1];
    add_user($odb);
    header("Refresh:0");
}
if ($_POST[login2] != '' and $_POST[password2] != '' and $_POST[mail2] != '' and $_POST[id2] != ''){
    $adb['id'] = $_POST[id2];
    $adb['login'] = $_POST[login2];
    $adb['password'] = $_POST[password2];
    $adb['mail'] = $_POST[mail2];
    $adb['phone'] = $_POST[phone2];
    $adb['city'] = $_POST[city2];
    upd_user($adb);
    header("Refresh:0");
}
if (isset($_POST[id3]) and $_POST[id3] != ''){
    del_user($_POST[id3]);
    header("Refresh:0");
}

if ($_POST[p24] != '' and $_POST[p26] != ''){
    $db1['p1'] = $_POST[p1];
    $db1['p2'] = $_POST[p2];
    $db1['p3'] = $_POST[p3];
    $db1['p4'] = $_POST[p4];
    $db1['p5'] = $_POST[p5];
    $db1['p6'] = $_POST[p6];
    $db1['p7'] = $_POST[p7];
    $db1['p8'] = $_POST[p8];
    $db1['p9'] = $_POST[p9];
    $db1['p10'] = $_POST[p10];
    $db1['p11'] = $_POST[p11];
    $db1['p12'] = $_POST[p12];
    $db1['p13'] = $_POST[p13];
    $db1['p14'] = $_POST[p14];
    $db1['p15'] = $_POST[p15];
    $db1['p16'] = $_POST[p16];
    $db1['p17'] = $_POST[p17];
    $db1['p18'] = $_POST[p18];
    $db1['p19'] = $_POST[p19];
    $db1['p20'] = $_POST[p20];
    $db1['p21'] = $_POST[p21];
    $db1['p22'] = $_POST[p22];
    $db1['p23'] = $_POST[p23];
    $db1['p24'] = $_POST[p24];
    $db1['p25'] = $_POST[p25];
    $db1['p26'] = $_POST[p26];
    add_cars($db1);
    header("Refresh:0");
}

if ($_POST[x24] != '' and $_POST[x26] != '' and $_POST[uid] != ''){
    $db2['id'] = $_POST[uid];
    $db2['p1'] = $_POST[x1];
    $db2['p2'] = $_POST[x2];
    $db2['p3'] = $_POST[x3];
    $db2['p4'] = $_POST[x4];
    $db2['p5'] = $_POST[x5];
    $db2['p6'] = $_POST[x6];
    $db2['p7'] = $_POST[x7];
    $db2['p8'] = $_POST[x8];
    $db2['p9'] = $_POST[x9];
    $db2['p10'] = $_POST[x10];
    $db2['p11'] = $_POST[x11];
    $db2['p12'] = $_POST[x12];
    $db2['p13'] = $_POST[x13];
    $db2['p14'] = $_POST[x14];
    $db2['p15'] = $_POST[x15];
    $db2['p16'] = $_POST[x16];
    $db2['p17'] = $_POST[x17];
    $db2['p18'] = $_POST[x18];
    $db2['p19'] = $_POST[x19];
    $db2['p20'] = $_POST[x20];
    $db2['p21'] = $_POST[p21];
    $db2['p22'] = $_POST[x22];
    $db2['p23'] = $_POST[x23];
    $db2['p24'] = $_POST[x24];
    $db2['p25'] = $_POST[x25];
    $db2['p26'] = $_POST[x26];
    upd_cars($db2);
    header("Refresh:0");
}
if ($_POST[did] != ''){
    del_cars($_POST[did]);
    header("Refresh:0");
}


echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "	<meta charset=\"UTF-8\">\n";
echo "	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n";
echo "    <!-- Bootstrap CSS -->\n";
echo "    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\" integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\" crossorigin=\"anonymous\">\n";
echo "	<title>Admin</title>\n";
echo "</head>\n";
echo "<body class=\"bg-light\">\n";
echo "	<div class=\"container-fluid bg-dark\">\n";
echo "		<div class=\"row\">\n";
echo "			<div class=\"mx-auto text-light\" style=\"width: 450px;\">\n";
echo "				<h2>Страница администратора</h2>\n";
echo "			</div>\n";
echo "		</div>\n";
echo "	</div>\n";
echo "\n";
echo "	<div class=\"container-fluid\">\n";
echo "		<div class=\"row\">\n";
echo "			<div class=\"col-4\">\n";

echo "              <h4 class=\"mx-auto\" style=\"width: 270px;\">Добавить пользователя</h4>\n";
echo "				<form method=\"post\">\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"Почта\" name=\"mail1\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"Пароль\" name=\"password1\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"Логин\" name=\"login1\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"Телефон\" name=\"phone1\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"Город\" name=\"city1\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row mx-auto\" style=\"width: 100px;\">\n";
echo "						<button type=\"submit\" class=\"btn btn-dark\" style=\"margin-top: 5px;\">Добавить</button>\n";
echo "					</div>\n";
echo "				</form>\n";
echo "				<h4 class=\"mx-auto\" style=\"width: 260px;\">Изменить запись по id</h4>\n";
echo "				<form method=\"post\">\n";
echo "					<div class=\"row\">\n";
echo "					    <div class=\"col\">\n";
echo "						    <input type=\"text\" class=\"form-control\" placeholder=\"ID\" name=\"id2\">\n";
echo "					    </div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"Почта\" name=\"mail2\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"Пароль\" name=\"password2\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"Логин\" name=\"login2\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"Телефон\" name=\"phone2\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"Город\" name=\"city2\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row mx-auto\" style=\"width: 150px;\">\n";
echo "						<button type=\"submit\" class=\"btn btn-dark\" style=\"margin-top: 5px;\">Изменить запись</button>\n";
echo "					</div>\n";
echo "				</form>\n";
echo "				<h4 class=\"mx-auto\" style=\"width: 250px;\">Удалить запись по id</h4>\n";
echo "				<form method=\"post\">\n";
echo "					<div class=\"row mx-auto\" style=\"width: 100px;\">\n";
echo "						<input type=\"text\" style=\"margin-bottom: 5px;\" class=\"form-control\" placeholder=\"ID\" name=\"id3\">\n";
echo "					</div>\n";
echo "					<div class=\"row mx-auto\" style=\"width: 140px;\">\n";
echo "						<button type=\"submit\" class=\"btn btn-dark\" style=\"margin-top: 5px;\">Удалить запись</button>\n";
echo "					</div>\n";
echo "				</form>\n";

echo "				<h4 class=\"mx-auto\" style=\"width: 270px;\">Таблица пользователей</h4>\n";
echo "				<table class=\"table table-bordered table-dark\">\n";
echo "					<thead>\n";
echo "						<tr>\n";
echo "							<th scope=\"col\">id</th>\n";
echo "							<th scope=\"col\">Почта</th>\n";
echo "							<th scope=\"col\">Пароль</th>\n";
echo "							<th scope=\"col\">Логин</th>\n";
echo "							<th scope=\"col\">Телефон</th>\n";
echo "							<th scope=\"col\">Город</th>\n";
echo "						</tr>\n";
echo "					</thead>\n";
echo "					<tbody>\n";
while ($line = pg_fetch_array($result, null, PGSQL_ASSOC)) {
    echo "						<tr>\n";
    echo "							<th scope=\"row\">$line[id]</th>\n";
    echo "							<td>$line[email]</td>\n";
    echo "							<td>$line[password]</td>\n";
    echo "							<td>$line[login]</td>\n";
    echo "							<td>$line[phone]</td>\n";
    echo "							<td>$line[city]</td>\n";
    echo "						</tr>\n";
}
echo "					</tbody>\n";
echo "				</table>\n";
echo "			</div>\n";
echo "			<div class=\"col-8\">\n";

echo "              <h4 class=\"mx-auto\" style=\"width: 270px;\">Добавить автомобиль</h4>\n";
echo "				<form method=\"post\">\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"тип кузова\" name=\"p1\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"кол-во дверей\" name=\"p2\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"кол-во мест\" name=\"p3\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"класс авто\" name=\"p4\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"положение руля\" name=\"p5\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"производитель\" name=\"p6\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"выпуск с\" name=\"p7\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"выпуск по\" name=\"p8\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"обьем двиг.\" name=\"p9\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"лс/квт/об\" name=\"p10\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"Н/об\" name=\"p11\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"наддув\" name=\"p12\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"подача топлива\" name=\"p13\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"кол-во клапанов\" name=\"p14\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"топливо\" name=\"p15\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"привод\" name=\"p16\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"тип КПП\" name=\"p17\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"под. перед\" name=\"p18\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"под. зад\" name=\"p19\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"до 100 км/ч\" name=\"p20\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"расх. город\" name=\"p21\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"расх. трасса\" name=\"p22\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"расх. смеш\" name=\"p23\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"название маш.\" name=\"p24\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"путь до фото\" name=\"p25\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"марка\" name=\"p26\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row mx-auto\" style=\"width: 100px;\">\n";
echo "						<button type=\"submit\" class=\"btn btn-dark\" style=\"margin-top: 5px;\">Добавить</button>\n";
echo "					</div>\n";
echo "				</form>\n";
echo "				<h4 class=\"mx-auto\" style=\"width: 260px;\">Изменить запись по id</h4>\n";
echo "				<form method=\"post\">\n";
echo "					<div class=\"row mx-auto\" style=\"width: 200px;\">\n";
echo "						<input type=\"text\" style=\"margin-bottom: 5px;\" class=\"form-control\" placeholder=\"ID\" name=\"uid\">\n";
echo "					</div>\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"тип кузова\" name=\"x1\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"кол-во дверей\" name=\"x2\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"кол-во мест\" name=\"x3\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"класс авто\" name=\"x4\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"положение руля\" name=\"x5\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"производитель\" name=\"x6\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"выпуск с\" name=\"x7\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"выпуск по\" name=\"x8\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"обьем двиг.\" name=\"x9\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"лс/квт/об\" name=\"x10\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"Н/об\" name=\"x11\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"наддув\" name=\"x12\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"подача топлива\" name=\"x13\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"кол-во клапанов\" name=\"x14\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"топливо\" name=\"x15\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"привод\" name=\"x16\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"тип КПП\" name=\"x17\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"под. перед\" name=\"x18\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"под. зад\" name=\"x19\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"до 100 км/ч\" name=\"x20\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"расх. город\" name=\"x21\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"расх. трасса\" name=\"x22\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"расх. смеш\" name=\"x23\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row\">\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"название маш.\" name=\"x24\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"путь до фото\" name=\"x25\">\n";
echo "						</div>\n";
echo "						<div class=\"col\">\n";
echo "							<input type=\"text\" class=\"form-control\" placeholder=\"марка\" name=\"x26\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"row mx-auto\" style=\"width: 150px;\">\n";
echo "						<button type=\"submit\" class=\"btn btn-dark\" style=\"margin-top: 5px;\">Изменить запись</button>\n";
echo "					</div>\n";
echo "				</form>\n";
echo "				<h4 class=\"mx-auto\" style=\"width: 250px;\">Удалить запись по id</h4>\n";
echo "				<form method=\"post\">\n";
echo "					<div class=\"row mx-auto\" style=\"width: 100px;\">\n";
echo "						<input type=\"text\" style=\"margin-bottom: 5px;\" class=\"form-control\" placeholder=\"ID\" name=\"did\">\n";
echo "					</div>\n";
echo "					<div class=\"row mx-auto\" style=\"width: 140px;\">\n";
echo "						<button type=\"submit\" class=\"btn btn-dark\" style=\"margin-top: 5px;margin-bottom: 10px;\">Удалить запись</button>\n";
echo "					</div>\n";
echo "				</form>\n";

echo "                  <table class=\"table table-bordered table-dark\">\n";
echo "					<thead>\n";
echo "						<tr>\n";
echo "							<th scope=\"col\">id</th>\n";
echo "							<th scope=\"col\">Авто</th>\n";
echo "						</tr>\n";
echo "					</thead>\n";
echo "					<tbody>\n";
while ($car = pg_fetch_array($cars, null, PGSQL_ASSOC)) {
    echo "						<tr>\n";
    echo "							<th scope=\"row\">$car[id]</th>\n";
    echo "							<td>$car[nameauto]</td>\n";
    echo "						</tr>\n";
}
echo "					</tbody>\n";
echo "				</table>\n";

echo "			</div>\n";
echo "		</div>\n";
echo "	</div>\n";
echo "\n";
echo "	<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\n";
echo "    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\" crossorigin=\"anonymous\"></script>\n";
echo "    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>\n";
echo "	<script>document.write('<script src=\"http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1\"></' + 'script>')</script>\n";
echo "</body>\n";
echo "</html>\n";


pg_close($dbconn);
